const courses = [
    {
        id: 1,
        code: 'ITCP 105',
        prerequisite_id: null, 
        description: 'Computer Programming 1', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 1,
    },
    {
        id: 2,
        code: 'ITAM 132',
        prerequisite_id: null, 
        description: 'Applied Engineering Mathematics ', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 1,
    },
    {
        id: 3,
        code: 'GEUS 201',
        prerequisite_id: null, 
        description: 'Understanding the Self', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 1,
    },
    {
        id: 4,
        code: 'GEPH 202',
        prerequisite_id: null, 
        description: 'Readings in Philippine History', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 1,
    },
    {
        id: 5,
        code: 'RESH 401',
        prerequisite_id: null, 
        description: 'Salvation History', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 1,
    },
    {
        id: 6,
        code: 'PATH Fit 100',
        prerequisite_id: null, 
        description: 'Physical Activities Towards Health and Fitness Movement Competency Training', 
        grade: null, 
        total_units: 2,
        lec_units: 2,
        lab_units: 0,
        year: 1,
        term: 1,
    },
    {
        id: 7,
        code: 'NSTP 201',
        prerequisite_id: null, 
        description: 'National Service Training Program 1', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 1,
    },

    // Second Term
    {
        id: 8,
        code: 'ITIC 102',
        prerequisite_id: null, 
        description: 'Introduction to Computing', 
        grade: null, 
        total_units: 2,
        lec_units: 2,
        lab_units: 0,
        year: 1,
        term: 2,
    },
    {
        id: 9,
        code: 'GEES 210',
        prerequisite_id: null, 
        description: 'Environmental Science', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 2,
    },
    {
        id: 10,
        code: 'GECW 203',
        prerequisite_id: null, 
        description: 'The Contemporary World', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 2,
    },
    {
        id: 11,
        code: 'GEMM 204',
        prerequisite_id: null, 
        description: 'Mathematics in the Modern World', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 2,
    },
    {
        id: 12,
        code: 'RECM 402',
        prerequisite_id: 5, 
        description: 'Christiology and Mariology', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 2,
    },
    {
        id: 13,
        code: 'PATH Fit 200',
        prerequisite_id: 6, 
        description: 'Physical Activities Towards Health and Fitness Exercise Based Fitness Activities', 
        grade: null, 
        total_units: 2,
        lec_units: 2,
        lab_units: 0,
        year: 1,
        term: 2,
    },
    {
        id: 14,
        code: 'NSTP 202',
        prerequisite_id: 7, 
        description: 'CWTS', 
        grade: null, 
        total_units: 3,
        lec_units: 3,
        lab_units: 0,
        year: 1,
        term: 2,
    },
]

export default courses;